// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbtjpbauothcawqomgne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidGpwYmF1b3RoY2F3cW9tZ25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5MTY5ODAsImV4cCI6MjA4ODQ5Mjk4MH0.DdgXoTn6yqbDBbt5VbmBI6GL671aj91ZT0OxERYsmk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});